FROM node:22-alpine
RUN apk add --no-cache openssl
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 5000
CMD ["sh", "-c", "node prisma/wait-for-db.js && npx prisma migrate deploy && npx ts-node-dev --respawn --transpile-only src/index.ts"]
